apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index
data:
  index.html: |

    <!DOCTYPE html>
    <html>
    <head>
    <title>Welcome to nginx!</title>
    </head>
    <body>
    <h1>Code.education Rocks</h1>
    </body>
    </html>
